**Adaboost**

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
df = sns.load_dataset('iris')
df['species'] = df['species'].map({'setosa':0,'versicolor':1,'virginica':2}).astype(int)
df

sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [12]:
X = df.iloc[: , :-1]
y = df.iloc[: , -1]

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [14]:
len(X_train),len(y_train)

(120, 120)

In [15]:
len(X_test),len(y_test)

(30, 30)

In [17]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

In [18]:
import warnings
warnings.filterwarnings('ignore')

In [19]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.ensemble import AdaBoostClassifier

In [20]:
values = [3,5,7,9,11]
for i in values:
  reg = AdaBoostClassifier(estimator=lr,n_estimators=i)
  reg.fit(X_train,y_train)
  print(f'Number of LR are : {i} and Train Accuracy was : {reg.score(X_train,y_train)}')
  print(f'Number of LR are : {i} and Test Accuracy was : {reg.score(X_test,y_test)}')
  print(f'When LR : {i} -> Confusion Matrix was : {confusion_matrix(y_test,reg.predict(X_test))}')
  print(f'-------------------------------------------------------------')

Number of LR are : 3 and Train Accuracy was : 0.875
Number of LR are : 3 and Test Accuracy was : 0.9666666666666667
When LR : 3 -> Confusion Matrix was : [[10  0  0]
 [ 0  9  0]
 [ 0  1 10]]
-------------------------------------------------------------
Number of LR are : 5 and Train Accuracy was : 0.8666666666666667
Number of LR are : 5 and Test Accuracy was : 0.9333333333333333
When LR : 5 -> Confusion Matrix was : [[10  0  0]
 [ 0  9  0]
 [ 0  2  9]]
-------------------------------------------------------------
Number of LR are : 7 and Train Accuracy was : 0.8666666666666667
Number of LR are : 7 and Test Accuracy was : 0.9333333333333333
When LR : 7 -> Confusion Matrix was : [[10  0  0]
 [ 0  9  0]
 [ 0  2  9]]
-------------------------------------------------------------
Number of LR are : 9 and Train Accuracy was : 0.8666666666666667
Number of LR are : 9 and Test Accuracy was : 0.9333333333333333
When LR : 9 -> Confusion Matrix was : [[10  0  0]
 [ 0  9  0]
 [ 0  2  9]]
-----------

**Gradient_Boosting**

In [21]:
lr_values = np.random.rand(10,10)
lr_values = lr_values.ravel()
lr_values

array([0.70325447, 0.18280649, 0.50489123, 0.01500053, 0.8429041 ,
       0.61342001, 0.45125821, 0.36910365, 0.48468063, 0.1835459 ,
       0.94269287, 0.50273123, 0.03753419, 0.07124307, 0.55528471,
       0.14336178, 0.43437112, 0.48363088, 0.23760625, 0.23432948,
       0.69273229, 0.92639795, 0.95616539, 0.77982692, 0.6573478 ,
       0.9211809 , 0.29976504, 0.51336043, 0.68887286, 0.52094441,
       0.60221812, 0.56764063, 0.97024292, 0.93983446, 0.71158849,
       0.25835345, 0.74658855, 0.7649279 , 0.7385537 , 0.88841548,
       0.18916772, 0.51383141, 0.47646365, 0.40120994, 0.56371798,
       0.74358424, 0.857904  , 0.04360122, 0.29444063, 0.52260732,
       0.4529385 , 0.51761254, 0.57829372, 0.63690005, 0.88422445,
       0.29617628, 0.05059177, 0.38630607, 0.76140234, 0.37752382,
       0.33631717, 0.06619179, 0.1462568 , 0.66830752, 0.95064906,
       0.66794549, 0.57332412, 0.23567613, 0.53195492, 0.85097324,
       0.35969859, 0.55122326, 0.39044068, 0.14964539, 0.94775

In [23]:
from sklearn.ensemble import GradientBoostingClassifier
lr_values = np.random.rand(10,10)
lr_values = lr_values.ravel()
for i in lr_values:
  gb = GradientBoostingClassifier(n_estimators=11,learning_rate=i)
  gb.fit(X_train,y_train)
  print(f'Learning Rate value : {i} and Train accuracy was : {gb.score(X_train,y_train)}')
  print(f'Learning Rate value : {i} and Test accuracy was : {gb.score(X_test,y_test)}')
  print(f'Learning Rate value : {i} -> Confusion Matrix was : {confusion_matrix(y_test,gb.predict(X_test))}')
  print()

Learning Rate value : 0.8507463212244282 and Train accuracy was : 1.0
Learning Rate value : 0.8507463212244282 and Test accuracy was : 1.0
Learning Rate value : 0.8507463212244282 -> Confusion Matrix was : [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Learning Rate value : 0.6774155847089138 and Train accuracy was : 1.0
Learning Rate value : 0.6774155847089138 and Test accuracy was : 1.0
Learning Rate value : 0.6774155847089138 -> Confusion Matrix was : [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Learning Rate value : 0.69177360025293 and Train accuracy was : 1.0
Learning Rate value : 0.69177360025293 and Test accuracy was : 1.0
Learning Rate value : 0.69177360025293 -> Confusion Matrix was : [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Learning Rate value : 0.9397417161357312 and Train accuracy was : 1.0
Learning Rate value : 0.9397417161357312 and Test accuracy was : 1.0
Learning Rate value : 0.9397417161357312 -> Confusion Matrix was : [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Learning Rate value : 0.828116

**Xtreme_Gradient_Boosting**

In [24]:
import xgboost
from xgboost import XGBClassifier

lr_values = np.random.rand(10,10)
lr_values = lr_values.ravel()
for i in lr_values:
  xg = XGBClassifier(n_estimators=11,learning_rate=i)
  xg.fit(X_train,y_train)
  print(f'Learning Rate value : {i} and Train accuracy was : {xg.score(X_train,y_train)}')
  print(f'Learning Rate value : {i} and Test accuracy was : {xg.score(X_test,y_test)}')
  print(f'Learning Rate value : {i} -> Confusion Matrix was : {confusion_matrix(y_test,xg.predict(X_test))}')
  print()

Learning Rate value : 0.7304733072026023 and Train accuracy was : 1.0
Learning Rate value : 0.7304733072026023 and Test accuracy was : 1.0
Learning Rate value : 0.7304733072026023 -> Confusion Matrix was : [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Learning Rate value : 0.25055506271770966 and Train accuracy was : 0.9833333333333333
Learning Rate value : 0.25055506271770966 and Test accuracy was : 1.0
Learning Rate value : 0.25055506271770966 -> Confusion Matrix was : [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Learning Rate value : 0.9592973580780932 and Train accuracy was : 1.0
Learning Rate value : 0.9592973580780932 and Test accuracy was : 1.0
Learning Rate value : 0.9592973580780932 -> Confusion Matrix was : [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Learning Rate value : 0.11546827341256305 and Train accuracy was : 0.975
Learning Rate value : 0.11546827341256305 and Test accuracy was : 1.0
Learning Rate value : 0.11546827341256305 -> Confusion Matrix was : [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

L

**SVM**

In [25]:
from sklearn.svm import SVC
reg_svm = SVC(kernel='rbf')
reg_svm.fit(X_train,y_train)

SVC()

In [26]:
print(f'Train Accuracy : {reg_svm.score(X_train,y_train)}')
print(f'Test Accuracy : {reg_svm.score(X_test,y_test)}')

Train Accuracy : 0.975
Test Accuracy : 1.0


**cross_validation**

In [27]:
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
knn_reg = KNeighborsClassifier()

In [28]:
X.shape

(150, 4)

In [30]:
accs = cross_val_score(knn_reg,X,y,cv=15)
print(accs)
print(sum(accs) / 15.0)

[1.  1.  0.9 1.  1.  1.  0.8 1.  1.  0.9 1.  1.  1.  1.  1. ]
0.9733333333333333
